language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-25.0.2
    - android-25
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-google-google_play_services
  licenses:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
script:
    - cp gradle.properties.example gradle.properties
    - ./gradlew clean assembleDebug testDebug